name: Build PPR

on:
  push:
    branches: [ WaymarksLib ]
  pull_request:
    branches: [ WaymarksLib ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    - name: Restore Nuget Packages
      run: nuget restore PaisleyPark.sln
    - name: Define VERSION
      run: |
        $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
        $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
        $env:BRANCH = $env:GITHUB_REF -replace '.*/'
        ($env:REPO_NAME) >> VERSION
        ($env:BRANCH) >> VERSION
        ($env:COMMIT) >> VERSION
    - name: Build DotNet4
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"           
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\PaisleyPark.sln /p:Configuration=Release
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
          name: PaisleyParkR-artifact
          path: PaisleyPark\bin\x64\Release
